/*
 * Copyright (C) 2024 Jesus del Buey Jiménez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0
 */
package main;

import java.awt.Font;
import java.util.Properties;
import java.util.ResourceBundle;

/**
 *
 * @author Jesus.delBuey
 */
public class AcercaDe extends javax.swing.JDialog {

    ResourceBundle idioma = Procesador.idioma;

    /**
     * Creates new form AcercaDe
     *
     * @param parent JFrame padre, la ventana principal
     * @param modal Recibe si el diálogo será modal o no
     */
    public AcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        InicializarFormulario();
    }

    private void InicializarFormulario() {
        // Pongo el icono de la aplicación
        this.setIconImage(Config.getIconoAplic().getImage());
        // Coloco el formulario en el centro de la pantalla
        Procesador.Centrame(this);
        StringBuilder texto = new StringBuilder();

        // Ver propiedades del sistema
        Properties pros = System.getProperties();
//        pros.list(System.out);

        // En Netbeans, da null, no lee bien el manifest que puesto en el POM; por tanto concat da error. Así no, añade "null"
        String dato;
        texto.append(idioma.getString("AcercaDe.aplicacion.nombre"));
        texto.append(getClass().getPackage().getImplementationTitle());
        texto.append("\n");
        texto.append(idioma.getString("AcercaDe.aplicacion.version"));
        texto.append(getClass().getPackage().getImplementationVersion());
        texto.append("\n");
        texto.append(idioma.getString("AcercaDe.os.name").concat(pros.get("os.name").toString().concat("\n")));
        texto.append(idioma.getString("AcercaDe.os.arch").concat(pros.get("os.arch").toString().concat("\n")));
        dato = (pros.get("native.encoding") == null) ? "N/A" : pros.get("native.encoding").toString();
        texto.append(idioma.getString("AcercaDe.os.juegoCaracteres").concat(dato.concat("\n")));
        texto.append(idioma.getString("AcercaDe.user.language").concat(pros.get("user.language").toString().concat("\n")));
        texto.append(idioma.getString("AcercaDe.os.timeZone").concat(pros.get("user.timezone").toString().concat("\n")));
        texto.append(idioma.getString("AcercaDe.java.version").concat(pros.get("java.version").toString().concat("\n")));
        texto.append(idioma.getString("AcercaDe.java.vm.version").concat(pros.get("java.vm.version").toString().concat("\n")));
        texto.append(idioma.getString("AcercaDe.user.dir").concat(pros.get("user.dir").toString().concat("\n")));
        //texto.append(idioma.getString("AcercaDe.aplicacion.runs").concat(String.valueOf(Config.getMisRuns()).concat("\n")));
        //
        textoPropiedadesSistema.setText(texto.toString());
        textoPropiedadesSistema.setCaretPosition(0);
        textoPropiedadesSistema.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etqSplash = new javax.swing.JLabel();
        etqYo = new javax.swing.JLabel();
        btnVerLicencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoPropiedadesSistema = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("propiedades/Idioma"); // NOI18N
        setTitle(bundle.getString("VENTANAINICIO.TITULO")); // NOI18N
        setModal(true);
        setResizable(false);

        etqSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/splash.png"))); // NOI18N

        etqYo.setFont(Config.FUENTE_NORMAL.deriveFont(Font.BOLD)
        );
        etqYo.setText(bundle.getString("AcercaDe.etqYo.text")); // NOI18N

        btnVerLicencia.setFont(Config.FUENTE_NORMAL);
        btnVerLicencia.setText(bundle.getString("AcercaDe.btnVerLicencia.text")); // NOI18N
        btnVerLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLicenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqYo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerLicencia)
                .addContainerGap())
            .addComponent(etqSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(etqSplash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etqYo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerLicencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoPropiedadesSistema.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textoPropiedadesSistema.setFont(Config.FUENTE_NORMAL);
        jScrollPane1.setViewportView(textoPropiedadesSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLicenciaActionPerformed
        // Muestro el texto de la licencia
        //DialogoLicencia ventaLic = new DialogoLicencia(this, true);
        new DialogoLicencia(this, true).setVisible(true);
    }//GEN-LAST:event_btnVerLicenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AcercaDe dialog = new AcercaDe(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerLicencia;
    private javax.swing.JLabel etqSplash;
    private javax.swing.JLabel etqYo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textoPropiedadesSistema;
    // End of variables declaration//GEN-END:variables
}
