/*
 * Copyright (C) 2024 Jesus del Buey Jiménez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0
 */

package main;

import java.awt.Font;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSlider;

/**
 *
 * @author Jesus.delBuey
 */
public class DialogoConfiguracion extends javax.swing.JDialog {


    /**
     * Creates new form DialogoConfiguracion
     *
     * @param parent Padre del diálogo
     * @param modal Si es modal o no
     */
    public DialogoConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        InicializarFormulario();
    }

    // Constructor sobrecargado con un JDialog, para que se puede llamar desde estos objetos
    public DialogoConfiguracion(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        InicializarFormulario();
    }

    private void InicializarFormulario() {
        // Coloco el formulario en el centro de la pantalla
        Procesador.Centrame(this);
        // Lo subo un poco sin salirme
        int postY = this.getLocation().y - 50;
        postY = postY < 5 ? 5 : postY;
        this.setLocation(this.getLocation().x, postY);
        // Cargo los valores iniciales
        etqIdiomaActual.setText(Config.getIdioma().getString("DialogoConfiguracion.etqIdiomaActual.text")
                + " - " + Locale.getDefault().getDisplayCountry() + " (" + Config.getIdiomaActual() + ") ");
        valorUmbralEsquinas.setText(Integer.toString(Config.getUmbralDeteccionEsquina()));
        valorUmbralMarcas.setText(Integer.toString(Config.getUmbralDeteccionMarca()));
        anchoRangoZonaEsquinas.setText(Integer.toString(Config.getRangoBusquedaEsquinas()));
        margenSuperiorSlider.setValue(Config.getMargenSuperiorHojaRecortar());
        margenIzquierdoSlider.setValue(Config.getMargenIzquierdoHojaRecortar());
        margenDerechoSlider.setValue(Config.getMargenDerechoHojaRecortar());
        anchoMarcasRespuestaSlider.setValue(Config.getAnchoMarcasRespuesta());
        
        // Asocio un evento de teclado F1 para lanzar la ayuda
        Procesador.asociaAyudaF1(btnAyuda, Config.getRutaAyudaConfiguracion());
    }

    private boolean guardarValores() {
        int valor;

        try {
            valor = Integer.parseInt(valorUmbralEsquinas.getText());
            if (valor >= 0 && valor < 256) {
                Config.setUmbralDeteccionEsquina(valor);
            } else {
                errorValores();
                return false;
            }
            valor = Integer.parseInt(valorUmbralMarcas.getText());
            if (valor >= 0 && valor < 256) {
                Config.setUmbralDeteccionMarca(valor);
            } else {
                errorValores();
                return false;
            }
            valor = Integer.parseInt(anchoRangoZonaEsquinas.getText());
            if (valor >= 20 && valor < 200) {
                Config.setRangoBusquedaEsquinas(valor);
            } else {
                errorValores();
                return false;
            }
            Config.setAnchoMarcasRespuesta(anchoMarcasRespuestaSlider.getValue());
            Config.setMargenDerechoHojaRecortar(margenDerechoSlider.getValue());
            Config.setMargenIzquierdoHojaRecortar(margenIzquierdoSlider.getValue());
            Config.setMargenSuperiorHojaRecortar(margenSuperiorSlider.getValue());
        } catch (NumberFormatException ex) {
            errorValores();
            return false;
        }
        return true;
    }

    private void errorValores() {
        JOptionPane.showOptionDialog(rootPane, Config.getIdioma().getString("DialogoConfiguracion.errorValores.text"), Config.getIdioma().getString("Error.text"),
                JOptionPane.NO_OPTION, JOptionPane.ERROR_MESSAGE, null, Config.OPCION_ACEPTAR, null);
        InicializarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUmbrales = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        etqIdiomaActual = new javax.swing.JLabel();
        panelValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorUmbralEsquinas = new javax.swing.JTextField();
        valorUmbralMarcas = new javax.swing.JTextField();
        anchoRangoZonaEsquinas = new javax.swing.JTextField();
        panelAnchoMarcas = new javax.swing.JPanel();
        etqAnchoRespuesta = new javax.swing.JLabel();
        anchoMarcasRespuestaSlider = new javax.swing.JSlider();
        etqAnchoRespuestaValor = new javax.swing.JLabel();
        panelRecorteMargenes = new javax.swing.JPanel();
        etqRecorteMargenes = new javax.swing.JLabel();
        margenSuperiorSlider = new javax.swing.JSlider();
        etqRecorteMargenSuperior = new javax.swing.JLabel();
        etqRecorteMargenSuperiorValor = new javax.swing.JLabel();
        etqRecorteMargenDerecho = new javax.swing.JLabel();
        margenDerechoSlider = new javax.swing.JSlider();
        etqRecorteMargenDerechoValor = new javax.swing.JLabel();
        etqRecorteMargenIzquierdo = new javax.swing.JLabel();
        margenIzquierdoSlider = new javax.swing.JSlider();
        etqRecorteMargenIzquierdoValor = new javax.swing.JLabel();
        btnValoresDefecto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("propiedades/Idioma"); // NOI18N
        setTitle(bundle.getString("DialogoConfiguracion.Titulo.text")); // NOI18N

        panelUmbrales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelUmbrales.setOpaque(false);

        btnAyuda.setBackground(new java.awt.Color(61, 117, 105));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Azul_ayuda_chic.png"))); // NOI18N
        btnAyuda.setToolTipText(bundle.getString("btnAyudaToolTip.text")); // NOI18N
        btnAyuda.setBorder(null);
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Azul_brillo_ayuda_chic.png"))); // NOI18N
        btnAyuda.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Azul_brillo_ayuda_chic.png"))); // NOI18N
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        etqIdiomaActual.setFont(Config.FUENTE_TITULO.deriveFont(Font.BOLD)
        );
        etqIdiomaActual.setText(bundle.getString("DialogoConfiguracion.etqIdiomaActual.text")); // NOI18N
        etqIdiomaActual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelValores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(Config.FUENTE_NORMAL);
        jLabel1.setText(bundle.getString("DialogoConfiguracion.jLabel1.text")); // NOI18N

        jLabel2.setFont(Config.FUENTE_NORMAL);
        jLabel2.setText(bundle.getString("DialogoConfiguracion.jLabel2.text")); // NOI18N

        jLabel3.setFont(Config.FUENTE_NORMAL);
        jLabel3.setText(bundle.getString("DialogoConfiguracion.jLabel3.text")); // NOI18N

        valorUmbralEsquinas.setFont(Config.FUENTE_NORMAL);
        valorUmbralEsquinas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorUmbralEsquinas.setMaximumSize(new java.awt.Dimension(60, 2147483647));
        valorUmbralEsquinas.setMinimumSize(new java.awt.Dimension(60, 26));
        valorUmbralEsquinas.setName(""); // NOI18N
        valorUmbralEsquinas.setPreferredSize(new java.awt.Dimension(60, 26));

        valorUmbralMarcas.setFont(Config.FUENTE_NORMAL);
        valorUmbralMarcas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorUmbralMarcas.setMaximumSize(new java.awt.Dimension(60, 2147483647));
        valorUmbralMarcas.setMinimumSize(new java.awt.Dimension(60, 26));
        valorUmbralMarcas.setPreferredSize(new java.awt.Dimension(60, 26));

        anchoRangoZonaEsquinas.setFont(Config.FUENTE_NORMAL);
        anchoRangoZonaEsquinas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        anchoRangoZonaEsquinas.setMaximumSize(new java.awt.Dimension(60, 2147483647));
        anchoRangoZonaEsquinas.setMinimumSize(new java.awt.Dimension(60, 26));
        anchoRangoZonaEsquinas.setPreferredSize(new java.awt.Dimension(60, 26));

        javax.swing.GroupLayout panelValoresLayout = new javax.swing.GroupLayout(panelValores);
        panelValores.setLayout(panelValoresLayout);
        panelValoresLayout.setHorizontalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anchoRangoZonaEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorUmbralMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorUmbralEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelValoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anchoRangoZonaEsquinas, valorUmbralEsquinas, valorUmbralMarcas});

        panelValoresLayout.setVerticalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorUmbralEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorUmbralMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anchoRangoZonaEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelValoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anchoRangoZonaEsquinas, valorUmbralEsquinas, valorUmbralMarcas});

        javax.swing.GroupLayout panelUmbralesLayout = new javax.swing.GroupLayout(panelUmbrales);
        panelUmbrales.setLayout(panelUmbralesLayout);
        panelUmbralesLayout.setHorizontalGroup(
            panelUmbralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUmbralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUmbralesLayout.createSequentialGroup()
                        .addComponent(btnAyuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etqIdiomaActual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUmbralesLayout.setVerticalGroup(
            panelUmbralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelUmbralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqIdiomaActual)
                    .addComponent(btnAyuda))
                .addGap(5, 5, 5)
                .addComponent(panelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAnchoMarcas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etqAnchoRespuesta.setFont(Config.FUENTE_TITULO.deriveFont(Font.BOLD));
        etqAnchoRespuesta.setText(bundle.getString("DialogoConfiguracion.etqAnchoRespuesta.text")); // NOI18N
        etqAnchoRespuesta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        anchoMarcasRespuestaSlider.setFont(Config.FUENTE_NORMAL);
        anchoMarcasRespuestaSlider.setMajorTickSpacing(5);
        anchoMarcasRespuestaSlider.setMaximum(10);
        anchoMarcasRespuestaSlider.setMinimum(5);
        anchoMarcasRespuestaSlider.setMinorTickSpacing(1);
        anchoMarcasRespuestaSlider.setPaintLabels(true);
        anchoMarcasRespuestaSlider.setPaintTicks(true);
        anchoMarcasRespuestaSlider.setSnapToTicks(true);
        anchoMarcasRespuestaSlider.setToolTipText(bundle.getString("DialogoConfiguracion.anchoMarcasRespuestaSlider.toolTipText")); // NOI18N
        anchoMarcasRespuestaSlider.setValue(5);
        anchoMarcasRespuestaSlider.setName(""); // NOI18N
        anchoMarcasRespuestaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anchoMarcasRespuestaSliderStateChanged(evt);
            }
        });

        etqAnchoRespuestaValor.setFont(Config.FUENTE_TITULO);
        etqAnchoRespuestaValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqAnchoRespuestaValor.setText(bundle.getString("DialogoConfiguracion.etqAnchoRespuestaValor.text")); // NOI18N
        etqAnchoRespuestaValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("DialogoConfiguracion.etqRecorteMargenDerechoValor.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, Config.FUENTE_NORMAL)); // NOI18N
        etqAnchoRespuestaValor.setMaximumSize(new java.awt.Dimension(80, 83));
        etqAnchoRespuestaValor.setMinimumSize(new java.awt.Dimension(57, 63));

        javax.swing.GroupLayout panelAnchoMarcasLayout = new javax.swing.GroupLayout(panelAnchoMarcas);
        panelAnchoMarcas.setLayout(panelAnchoMarcasLayout);
        panelAnchoMarcasLayout.setHorizontalGroup(
            panelAnchoMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnchoMarcasLayout.createSequentialGroup()
                .addGroup(panelAnchoMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnchoMarcasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(anchoMarcasRespuestaSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAnchoMarcasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(etqAnchoRespuesta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etqAnchoRespuestaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAnchoMarcasLayout.setVerticalGroup(
            panelAnchoMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnchoMarcasLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(etqAnchoRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anchoMarcasRespuestaSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnchoMarcasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqAnchoRespuestaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRecorteMargenes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelRecorteMargenes.setToolTipText(bundle.getString("DialogoConfiguracion.etqRecorteMargenes.tooltipText")); // NOI18N

        etqRecorteMargenes.setFont(Config.FUENTE_TITULO.deriveFont(Font.BOLD));
        etqRecorteMargenes.setText(bundle.getString("DialogoConfiguracion.etqRecorteMargenes.text")); // NOI18N
        etqRecorteMargenes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        margenSuperiorSlider.setFont(Config.FUENTE_NORMAL);
        margenSuperiorSlider.setMajorTickSpacing(5);
        margenSuperiorSlider.setMaximum(30);
        margenSuperiorSlider.setMinorTickSpacing(1);
        margenSuperiorSlider.setPaintLabels(true);
        margenSuperiorSlider.setPaintTicks(true);
        margenSuperiorSlider.setSnapToTicks(true);
        margenSuperiorSlider.setToolTipText("");
        margenSuperiorSlider.setName(""); // NOI18N
        margenSuperiorSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                margenSuperiorSliderStateChanged(evt);
            }
        });

        etqRecorteMargenSuperior.setFont(Config.FUENTE_NORMAL);
        etqRecorteMargenSuperior.setText(bundle.getString("DialogoConfiguracion.etqMargenSuperior.Text")); // NOI18N

        etqRecorteMargenSuperiorValor.setFont(Config.FUENTE_TITULO);
        etqRecorteMargenSuperiorValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqRecorteMargenSuperiorValor.setText(bundle.getString("DialogoConfiguracion.etqMargenSuperior.valor.text")); // NOI18N
        etqRecorteMargenSuperiorValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("DialogoConfiguracion.etqRecorteMargenIzquierdoValor.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, Config.FUENTE_NORMAL)); // NOI18N
        etqRecorteMargenSuperiorValor.setMaximumSize(new java.awt.Dimension(80, 500));
        etqRecorteMargenSuperiorValor.setMinimumSize(new java.awt.Dimension(57, 63));
        etqRecorteMargenSuperiorValor.setPreferredSize(new java.awt.Dimension(57, 63));

        etqRecorteMargenDerecho.setFont(Config.FUENTE_NORMAL);
        etqRecorteMargenDerecho.setText(bundle.getString("DialogoConfiguracion.etqRecorteMargenDerecho.text")); // NOI18N

        margenDerechoSlider.setFont(Config.FUENTE_NORMAL);
        margenDerechoSlider.setMajorTickSpacing(5);
        margenDerechoSlider.setMaximum(30);
        margenDerechoSlider.setMinorTickSpacing(1);
        margenDerechoSlider.setPaintLabels(true);
        margenDerechoSlider.setPaintTicks(true);
        margenDerechoSlider.setSnapToTicks(true);
        margenDerechoSlider.setToolTipText(bundle.getString("DialogoConfiguracion.margenDerechoSlider.toolTipText")); // NOI18N
        margenDerechoSlider.setName(""); // NOI18N
        margenDerechoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                margenDerechoSliderStateChanged(evt);
            }
        });

        etqRecorteMargenDerechoValor.setFont(Config.FUENTE_TITULO);
        etqRecorteMargenDerechoValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqRecorteMargenDerechoValor.setText(bundle.getString("DialogoConfiguracion.etqRecorteMargenDerechoValor.text")); // NOI18N
        etqRecorteMargenDerechoValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("DialogoConfiguracion.etqRecorteMargenIzquierdoValor.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, Config.FUENTE_NORMAL)); // NOI18N
        etqRecorteMargenDerechoValor.setMaximumSize(new java.awt.Dimension(80, 500));
        etqRecorteMargenDerechoValor.setMinimumSize(new java.awt.Dimension(57, 63));
        etqRecorteMargenDerechoValor.setPreferredSize(new java.awt.Dimension(57, 63));

        etqRecorteMargenIzquierdo.setFont(Config.FUENTE_NORMAL);
        etqRecorteMargenIzquierdo.setText(bundle.getString("DialogoConfiguracion.etqRecorteMargenIzquierdo.text")); // NOI18N

        margenIzquierdoSlider.setFont(Config.FUENTE_NORMAL);
        margenIzquierdoSlider.setMajorTickSpacing(5);
        margenIzquierdoSlider.setMaximum(10);
        margenIzquierdoSlider.setMinimum(-10);
        margenIzquierdoSlider.setMinorTickSpacing(1);
        margenIzquierdoSlider.setPaintLabels(true);
        margenIzquierdoSlider.setPaintTicks(true);
        margenIzquierdoSlider.setSnapToTicks(true);
        margenIzquierdoSlider.setToolTipText(bundle.getString("DialogoConfiguracion.margenIzquierdoSlider.toolTipText")); // NOI18N
        margenIzquierdoSlider.setValue(0);
        margenIzquierdoSlider.setName(""); // NOI18N
        margenIzquierdoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                margenIzquierdoSliderStateChanged(evt);
            }
        });

        etqRecorteMargenIzquierdoValor.setFont(Config.FUENTE_TITULO);
        etqRecorteMargenIzquierdoValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqRecorteMargenIzquierdoValor.setText(bundle.getString("DialogoConfiguracion.etqRecorteMargenIzquierdoValor.text")); // NOI18N
        etqRecorteMargenIzquierdoValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("DialogoConfiguracion.etqRecorteMargenIzquierdoValor.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, Config.FUENTE_NORMAL)); // NOI18N
        etqRecorteMargenIzquierdoValor.setMaximumSize(new java.awt.Dimension(80, 500));
        etqRecorteMargenIzquierdoValor.setMinimumSize(new java.awt.Dimension(57, 63));
        etqRecorteMargenIzquierdoValor.setPreferredSize(new java.awt.Dimension(57, 63));

        javax.swing.GroupLayout panelRecorteMargenesLayout = new javax.swing.GroupLayout(panelRecorteMargenes);
        panelRecorteMargenes.setLayout(panelRecorteMargenesLayout);
        panelRecorteMargenesLayout.setHorizontalGroup(
            panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqRecorteMargenes)
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqRecorteMargenIzquierdo)
                            .addComponent(etqRecorteMargenSuperior)
                            .addComponent(etqRecorteMargenDerecho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                                .addComponent(margenDerechoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etqRecorteMargenDerechoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(margenSuperiorSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(margenIzquierdoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etqRecorteMargenIzquierdoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etqRecorteMargenSuperiorValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        panelRecorteMargenesLayout.setVerticalGroup(
            panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqRecorteMargenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addComponent(margenSuperiorSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqRecorteMargenSuperior)
                            .addComponent(etqRecorteMargenSuperiorValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addComponent(margenIzquierdoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addComponent(etqRecorteMargenIzquierdo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addComponent(etqRecorteMargenIzquierdoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addComponent(margenDerechoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelRecorteMargenesLayout.createSequentialGroup()
                        .addGroup(panelRecorteMargenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqRecorteMargenDerecho)
                            .addComponent(etqRecorteMargenDerechoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );

        btnValoresDefecto.setFont(Config.FUENTE_NORMAL);
        btnValoresDefecto.setText(bundle.getString("DialogoConfiguracion.btnValoresDefecto.text")); // NOI18N
        btnValoresDefecto.setActionCommand(bundle.getString("DialogoConfiguracion.btnValoresDefecto.text")); // NOI18N
        btnValoresDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValoresDefectoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(Config.FUENTE_NORMAL);
        btnCancelar.setText(bundle.getString("DialogoConfiguracion.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(Config.FUENTE_NORMAL);
        btnConfirmar.setText(bundle.getString("DialogoConfiguracion.btnConfirmar.text")); // NOI18N
        btnConfirmar.setActionCommand(bundle.getString("DialogoConfiguracion.btnConfirmar.actionCommand")); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUmbrales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnchoMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRecorteMargenes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnValoresDefecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelUmbrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnchoMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRecorteMargenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar)
                    .addComponent(btnValoresDefecto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValoresDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValoresDefectoActionPerformed
        // Restaura los valores por defecto
        ValoresDefecto();
    }//GEN-LAST:event_btnValoresDefectoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Salgo sin guardar los cambios
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void margenSuperiorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_margenSuperiorSliderStateChanged
        // Cuando cambia el slider, cambio el valor de la propiedad de configuración.
        Config.setMargenSuperiorHojaRecortar(actualizaSlider(evt, etqRecorteMargenSuperiorValor));
    }//GEN-LAST:event_margenSuperiorSliderStateChanged

    private void margenDerechoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_margenDerechoSliderStateChanged
        // Cuando cambia el slider, cambio el valor de la propiedad de configuración.
        Config.setMargenDerechoHojaRecortar(actualizaSlider(evt, etqRecorteMargenDerechoValor));
    }//GEN-LAST:event_margenDerechoSliderStateChanged

    private void margenIzquierdoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_margenIzquierdoSliderStateChanged
        // Cuando cambia el slider, cambio el valor de la propiedad de configuración.
        Config.setMargenIzquierdoHojaRecortar(actualizaSlider(evt, etqRecorteMargenIzquierdoValor));
    }//GEN-LAST:event_margenIzquierdoSliderStateChanged

    private void anchoMarcasRespuestaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anchoMarcasRespuestaSliderStateChanged
        // Cuando cambia el slider, cambio el valor de la propiedad de configuración.
        Config.setAnchoMarcasRespuesta(actualizaSlider(evt, etqAnchoRespuestaValor));
    }//GEN-LAST:event_anchoMarcasRespuestaSliderStateChanged

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // Guardo los cambios hechos en la configuración
        if (guardarValores()) {
            Config.guardarConfiguracion();
        }
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        String error = Procesador.mostrarAyuda(Config.getRutaAyudaConfiguracion());
        if (!"".equals(error)) {
            Config.getLog().error(error);
            JOptionPane.showOptionDialog(rootPane, error, Config.getIdioma().getString("Error.text"),
                JOptionPane.NO_OPTION, JOptionPane.ERROR_MESSAGE, null, new String[]{Config.getIdioma().getString("Aceptar.text")}, Config.getIdioma().getString("Aceptar.text"));
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void ValoresDefecto() {
        // Restauro los valores de configuración por defecto
        Config.ValoresConfiguracionDefecto();
        //
        valorUmbralEsquinas.setText(String.valueOf(Config.getUmbralDeteccionEsquina()));
        valorUmbralMarcas.setText(String.valueOf(Config.getUmbralDeteccionMarca()));
        anchoRangoZonaEsquinas.setText(String.valueOf(Config.getRangoBusquedaEsquinas()));
        anchoMarcasRespuestaSlider.setValue(Config.getAnchoMarcasRespuesta());
        margenSuperiorSlider.setValue(Config.getMargenSuperiorHojaRecortar());
        margenIzquierdoSlider.setValue(Config.getMargenIzquierdoHojaRecortar());
        margenDerechoSlider.setValue(Config.getMargenDerechoHojaRecortar());
    }

    private int actualizaSlider(javax.swing.event.ChangeEvent evt, JLabel etiq) {
        // Actualizador gnerico de sliders
        JSlider slid = (JSlider) evt.getSource();
        etiq.setText("<html><strong>" + String.valueOf(slid.getValue()) + "</strong></html>");
        return slid.getValue();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Config.getLog().error(ex.getMessage());
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider anchoMarcasRespuestaSlider;
    private javax.swing.JTextField anchoRangoZonaEsquinas;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnValoresDefecto;
    private javax.swing.JLabel etqAnchoRespuesta;
    private javax.swing.JLabel etqAnchoRespuestaValor;
    private javax.swing.JLabel etqIdiomaActual;
    private javax.swing.JLabel etqRecorteMargenDerecho;
    private javax.swing.JLabel etqRecorteMargenDerechoValor;
    private javax.swing.JLabel etqRecorteMargenIzquierdo;
    private javax.swing.JLabel etqRecorteMargenIzquierdoValor;
    private javax.swing.JLabel etqRecorteMargenSuperior;
    private javax.swing.JLabel etqRecorteMargenSuperiorValor;
    private javax.swing.JLabel etqRecorteMargenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider margenDerechoSlider;
    private javax.swing.JSlider margenIzquierdoSlider;
    private javax.swing.JSlider margenSuperiorSlider;
    private javax.swing.JPanel panelAnchoMarcas;
    private javax.swing.JPanel panelRecorteMargenes;
    private javax.swing.JPanel panelUmbrales;
    private javax.swing.JPanel panelValores;
    private javax.swing.JTextField valorUmbralEsquinas;
    private javax.swing.JTextField valorUmbralMarcas;
    // End of variables declaration//GEN-END:variables
}
