/*
 * Copyright (C) 2024 Jesus del Buey Jiménez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0
 */
package main;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Jesus.delBuey
 */
public class DialogoInfo extends javax.swing.JDialog {

    /**
     * Creates new form DialogoModeloVinfo
     *
     * @param parent Objeto padre
     * @param modal Si es modal
     * @param ancho Ancho del diálogo
     * @param alto Alto del diálogo
     * @param titulo Titulo del dialogo
     * @param textoMensaje Texto a mostrar
     * @param tiempoSegundos Tiempo en segundos que estará visible, 0 si es permanente
     */
    public DialogoInfo(java.awt.Frame parent, boolean modal, int ancho, int alto, String titulo, String textoMensaje, int tiempoSegundos) {
        super(parent, modal);
        initComponents();
        InicializarFormulario(ancho, alto, titulo, textoMensaje, tiempoSegundos);
    }
    
    public DialogoInfo(java.awt.Dialog parent, boolean modal, int ancho, int alto, String titulo, String textoMensaje, int tiempoSegundos) {
        super(parent, modal);
        initComponents();
        InicializarFormulario(ancho, alto, titulo, textoMensaje, tiempoSegundos);
    }

    private void InicializarFormulario(int anchoDiag, int altoDiag, String tituloDiag, String txtMensaj, int tmpSeg) {
        this.setSize(anchoDiag, altoDiag);
        this.setTitle(tituloDiag);
        Procesador.Centrame(this);
        textoInfo.setContentType("text/html");
        textoInfo.setText(txtMensaj);
        textoInfo.setEditable(false);
        // Si ha especificado tiempo pongo un timer
        if (tmpSeg > 0) {
            Timer timer = new Timer(tmpSeg * 1000, (ActionEvent e) -> {
                setVisible(false);
                dispose();
            });

            // Iniciar el Timer
            timer.setRepeats(false); // Para Asegurarse de que el Timer solo se ejecute una vez
            timer.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoInfo = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("propiedades/Idioma"); // NOI18N
        setTitle(bundle.getString("DialogoInfo.title")); // NOI18N
        setFont(Config.FUENTE_NORMAL);

        textoInfo.setContentType(""); // NOI18N
        textoInfo.setFont(Config.FUENTE_TITULO);
        jScrollPane1.setViewportView(textoInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane textoInfo;
    // End of variables declaration//GEN-END:variables
}
